# Generated by Django 3.2.12 on 2023-05-30 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20230530_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorvarient',
            name='product_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sizevarient',
            name='product_value',
            field=models.IntegerField(default=0),
        ),
    ]
